apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: team-mutate-resource-labels
  annotations:
    policies.kyverno.io/title: Add Object Creator to labels
    policies.kyverno.io/category: Other
    policies.kyverno.io/severity: medium
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/minversion: 1.6.0
    kyverno.io/kubernetes-version: "1.23"
    policies.kyverno.io/subject: Group
    policies.kyverno.io/description: >-
      Adds a label with the user that created the object.
spec:
  background: true
  rules:
  - name: add-object-creator
    match:
      any:
      - resources:
          kinds:
            - "*"
        subjects:
        - kind: Group
          name: "team1"
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            "owner.example.com/{{request.userInfo.groups[?contains(@,':') == `false`] | [0] || ''}}": ""
            "team.example.com/{{request.userInfo.groups[?contains(@,':') == `false`] | [0] || ''}}": ""
