apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-daemonset
spec:
  selector:
      matchLabels:
        name: hello-daemonset
  template:
    metadata:
      labels:
        name: hello-daemonset
    spec:
      nodeSelector:
        node-role.kubernetes.io/no-sno: ""
      containers:
      - image: openshift/hello-openshift
        imagePullPolicy: Always
        name: registry
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      serviceAccount: default
      terminationGracePeriodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc
spec:
  selector:
    name: hello-daemonset
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-svc-nodeport
spec:
  type: LoadBalancer
  selector:
    name: hello-daemonset
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-svc
spec:
  host: hello-svc-telco.apps.qct8.karmalabs.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: hello-svc
