---
apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: pfcp-socket-size
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
    - data: |
        [main]
        summary=Description of pfcp-socket-size profile
        include=openshift-control-plane
        [sysctl]
        net.core.rmem_max=8388608
        net.core.wmem_max=8388608
      name: pfcp-socket-size-master
    - data: |
        [main]
        summary=Description of pfcp-socket-size profile
        include=openshift-node
        [sysctl]
        net.core.rmem_max=8388608
        net.core.wmem_max=8388608
      name: pfcp-socket-size-standard
  recommend:
    - match:
        - label: node-role.kubernetes.io/master
      priority: 10
      profile: pfcp-socket-size-master
    - match:
        - label: node-role.kubernetes.io/standard
      priority: 20
      profile: pfcp-socket-size-standard
