---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: master
  name: 40-load-kernel-modules-master
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:,
          mode: 420
          overwrite: true
          path: /etc/modprobe.d/kernel-blacklist.conf
        - contents:
            source: data:text/plain;charset=utf-8;base64,aXBfZ3JlCmlwNl90YWJsZXMKaXB0YWJsZV9tYW5nbGUKaXA2dGFibGVfbWFuZ2xlCmlwNnRhYmxlX2ZpbHRlcgppcHRhYmxlX2ZpbHRlcgppcDZ0X1JFSkVDVAppcHRfUkVKRUNUCnh0X1RDUE1TUwp4dF91MzIKeHRfbXVsdGlwb3J0Cnh0X3N0YXRpc3RpYwp4dF9tYXJrCnh0X2Nvbm50cmFjawp4dF9SRURJUkVDVAp4dF9vd25lcgppcHRhYmxlX25hdA==
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/kernel-load.conf
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 40-load-kernel-modules-worker
spec:
  config:
    ignition:
      version: 3.1.0
    storage:
      files:
        - contents:
            source: data:,
          mode: 420
          overwrite: true
          path: /etc/modprobe.d/kernel-blacklist.conf
        - contents:
            source: data:text/plain;charset=utf-8;base64,aXBfZ3JlCmlwNl90YWJsZXMKaXB0YWJsZV9tYW5nbGUKaXA2dGFibGVfbWFuZ2xlCmlwNnRhYmxlX2ZpbHRlcgppcHRhYmxlX2ZpbHRlcgppcDZ0X1JFSkVDVAppcHRfUkVKRUNUCnh0X1RDUE1TUwp4dF91MzIKeHRfbXVsdGlwb3J0Cnh0X3N0YXRpc3RpYwp4dF9tYXJrCnh0X2Nvbm50cmFjawp4dF9SRURJUkVDVAp4dF9vd25lcgppcHRhYmxlX25hdA==
          mode: 420
          overwrite: true
          path: /etc/modules-load.d/kernel-load.conf
