FROM python:3.9-slim-bullseye

MAINTAINER Karim Boumedhel <karimboumedhel@gmail.com>

LABEL name="karmab/nodeip-hack" \
      maintainer="karimboumedhel@gmail.com" \
      vendor="Karmalabs" \
      version="latest" \
      release="0" \
      summary="Node ip hack" \
      description="Node ip hack"

# RUN echo 'APT::Install-Recommends "0";' >> /etc/apt/apt.conf && echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf && apt-get update && apt-get -y install python3-netifaces python3-ipaddr && apt -y autoremove && apt-get clean all
RUN pip3 install netifaces ipaddr
ADD hack.py /

CMD [ "/usr/local/bin/python3", "-u", "/hack.py" ]
