apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: hack-nodeip-configuration
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
        - contents:
            source: data:,KUBELET_NODEIP_HINT=192.168.122.3%0A
            verification: {}
          mode: 420
          path: /etc/default/nodeip-configuration
