---
apiVersion: v1
kind: Secret
metadata:
  name: master-0-ztp
  namespace: ztp
data:
  username: "dGVzdA=="
  password: "dGVzdA=="
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: master-1-ztp
  namespace: ztp
data:
  username: "dGVzdA=="
  password: "dGVzdA=="
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: master-2-ztp
  namespace: ztp
data:
  username: "dGVzdA=="
  password: "dGVzdA=="
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-0-ztp
  namespace: ztp
data:
  username: "dGVzdA=="
  password: "dGVzdA=="
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-1-ztp
  namespace: ztp
data:
  username: "dGVzdA=="
  password: "dGVzdA=="
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: worker-2-ztp
  namespace: ztp
data:
  username: "dGVzdA=="
  password: "dGVzdA=="
type: Opaque
