apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: sno-placement
  namespace: hoh-policies
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
    - key: sno
      operator: In
      values:
      - "true"
