apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-deploy-sno-app
  namespace: hoh-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures, PR.PT Protective Technology
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration, PR.PT-3 Least Functionality
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deploy-app-reversewordsapp-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - hoh-policies
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: reverse-words-app
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deploy-app-reversewords-deployment
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - hoh-policies
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: reverse-words
                  namespace: reverse-words-app
                  labels:
                    app: reverse-words
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: reverse-words
                  template:
                    metadata:
                      labels:
                        app: reverse-words
                    spec:
                      containers:
                      - name: reverse-words
                        image: quay.io/mavazque/reversewords:latest
                        ports:
                        - containerPort: 8080
                          name: http
                        env:
                        - name: RELEASE
                          value: "Base release"
                        livenessProbe:
                          httpGet:
                            path: /health
                            port: 8080
                          initialDelaySeconds: 5
                          timeoutSeconds: 2
                          periodSeconds: 15
                        readinessProbe:
                          httpGet:
                            path: /health
                            port: 8080
                          initialDelaySeconds: 10
                          timeoutSeconds: 2
                          periodSeconds: 15
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-deploy-reversewordsapp-sno
  namespace: hoh-policies
placementRef:
  name: sno-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-deploy-sno-app
    kind: Policy
    apiGroup: policy.open-cluster-management.io
