apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-deploy-nginx-app
  namespace: hoh-policies
  annotations:
    policy.open-cluster-management.io/standards: NIST-CSF
    policy.open-cluster-management.io/categories: PR.IP Information Protection Processes and Procedures, PR.PT Protective Technology
    policy.open-cluster-management.io/controls: PR.IP-1 Baseline Configuration, PR.PT-3 Least Functionality
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deploy-app-nginx-ns
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - hoh-policies
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Namespace
                apiVersion: v1
                metadata:
                  name: nginx-app
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-deploy-app-nginx-deployment
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - hoh-policies
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: apps/v1
                kind: Deployment
                metadata:
                  name: nginx
                  namespace: nginx-app
                  labels:
                    app: nginx
                spec:
                  replicas: 1
                  selector:
                    matchLabels:
                      app: nginx
                  template:
                    metadata:
                      labels:
                        app: nginx
                    spec:
                      containers:
                      - name: nginx
                        image: quay.io/mavazque/nginx:latest
                        ports:
                        - containerPort: 80
                          name: http
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-deploy-nginx-europe
  namespace: hoh-policies
placementRef:
  name: europe-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-deploy-nginx-app
    kind: Policy
    apiGroup: policy.open-cluster-management.io
