apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: test-pod-all-tolerations
  name: test-pod-all-tolerations
spec:
  tolerations:
  - operator: "Exists"
  containers:
  - image: quay.io/mavazque/reversewords:latest
    name: test-pod-all-tolerations
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
